# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-macos-amd64:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20

    # - name: Build
    #   run: go build -v ./...

    - uses: actions-rs/cargo@v1
      with:
        command: GOOS=darwin GOARCH=amd64 go build -v ./...
    - uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/keyvalDetector
        asset_name: keyvalDetector-darwin-amd64
        tag: ${{ github.ref }}

    # - name: Test
    #   run: go test -v ./...
